src/CkeckIn/Models/Questions/Answer/AnswerCreateView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CkeckIn.Models.Questions.Answer
{
    public class AnswerCreateView
    {
        [Display(Name ="Вопрос")]
        public Guid QuestionId { get; set; }

        public SelectList QuestionSelectList { get; set; }


        [Display(Name ="Текст ответа")]
        public string AnswerMessage { get; set; }

        [Range(0, 10)]
        [Display(Name ="Оценка за ответ")]
        public short Mark { get; set; }
    }
}

src/CkeckIn/Models/Questions/Answer/AnswerDetailView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CkeckIn.Models.Questions.Answer
{
    public class AnswerDetailView : AnswerView
    {

    }
}

src/CkeckIn/Models/Questions/Answer/AnswerEntity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using CkeckIn.Models.Questions.Question;
using CkeckIn.Models.Questions.Test;
using CkeckIn.Models.Questions.Thread;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace CkeckIn.Models.Questions.Answer
{
    public class AnswerEntity
    {
        public Guid AnswerId { get; set; }
        public Guid QuestionId { get; set; }

        public string AnswerMessage { get; set; }
        public short Mark { get; set; }

        public virtual QuestionEntity QuestionEntity { get; set; }

        public AnswerView AsView()
        {
            Mapper.Initialize(c =>
                c.CreateMap<AnswerEntity, AnswerView>()
            );
            return Mapper.Map<AnswerView>(this);
        }

        public AnswerDetailView AsDetailView()
        {
            Mapper.Initialize(c =>
                c.CreateMap<AnswerEntity, AnswerDetailView>()
            );
            return Mapper.Map<AnswerDetailView>(this);
        }

        public static void Configuration(EntityTypeBuilder<AnswerEntity> b)
        {
            b.HasKey(p => p.AnswerId);
            b.Property(p => p.AnswerMessage).HasMaxLength(256);
        }

        public static AnswerEntity Factory(AnswerCreateView view)
        {
            Mapper.Initialize(c =>
                c.CreateMap<AnswerCreateView, AnswerEntity>()
                .ForMember(m => m.AnswerId, m => m.MapFrom(r => Guid.NewGuid()))
            );

            return Mapper.Map<AnswerEntity>(view);
        }
    }
}

src/CkeckIn/Models/Questions/Answer/AnswerView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CkeckIn.Models.Questions.Answer
{
    public class AnswerView
    {
        [Display(Name ="Ид ответа")]
        public Guid AnswerId { get; set; }

        public Guid QuestionId { get; set; }


        [Display(Name ="Ответ")]
        public string AnswerMessage { get; set; }

        [Display(Name ="Оценка за ответ")]
        public short Mark { get; set; }
    }
}

src/CkeckIn/Models/Questions/Discipline/DisciplineCreateView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CkeckIn.Models.Questions.Discipline
{
    public class DisciplineCreateView
    {
        [Display(Name ="Название дисциплины")]
        public string DisciplineName { get; set; }

    }
}

src/CkeckIn/Models/Questions/Discipline/DisciplineDetailView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CkeckIn.Models.Questions.Question;
using CkeckIn.Models.Questions.Thread;

namespace CkeckIn.Models.Questions.Discipline
{
    public class DisciplineDetailView : DisciplineView
    {
        public List<QuestionView> QuestionViews { get; set; }
    }
}

src/CkeckIn/Models/Questions/Discipline/DisciplineEntity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using CkeckIn.Models.Questions.Question;
using CkeckIn.Models.Questions.Thread;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace CkeckIn.Models.Questions.Discipline
{
    public enum DisciplineCourse : byte
    {
        All,
        C1 = 1,
        C2 = 2,
        C3 = 4,
        C4 = 8,
        C5 = 16,
        C6 = 32
    }

    public class DisciplineEntity
    {
        public Guid DisciplineId { get; set; }
        public string DisciplineName { get; set; }
        public DisciplineCourse Course { get; set; }

        public virtual List<ThreadEntity> ThreadEntities { get; set; } = new List<ThreadEntity>(64);

        public DisciplineView AsView()
        {
            Mapper.Initialize(c => 
                c.CreateMap<DisciplineEntity, DisciplineView>()
                .ForMember(m => m.ThreadViews, m => m.MapFrom(r => r.ThreadEntities.Take(5).Select(d => d.AsView()).ToList()))
            );
            return Mapper.Map<DisciplineView>(this);
        }

        public DisciplineDetailView AsDetailView()
        {
            Mapper.Initialize
            (
                c => c.CreateMap<DisciplineEntity, DisciplineDetailView>()
                .ForMember(m => m.ThreadViews, m => m.MapFrom(r => r.ThreadEntities.Select(d => d.AsView()).ToList()))
            );
            return Mapper.Map<DisciplineDetailView>(this);
        }

        public static void Configuration(EntityTypeBuilder<DisciplineEntity> b)
        {
            b.HasKey(p => p.DisciplineId);
            b.Property(p => p.DisciplineName).HasMaxLength(128);
            b.HasMany(p => p.ThreadEntities).WithOne(p => p.DisciplineEntity).HasForeignKey(p => p.DisciplineId);
        }


        public static DisciplineEntity Factory(DisciplineCreateView view)
        {
            Mapper.Initialize(c => c.CreateMap<DisciplineCreateView, DisciplineEntity>()
                .ForMember(m => m.DisciplineId, m => m.MapFrom(r => Guid.NewGuid()))
                .ForMember(m => m.ThreadEntities, m => m.Ignore())
            );

            return Mapper.Map<DisciplineEntity>(view);
        }
    }
}

src/CkeckIn/Models/Questions/Discipline/DisciplineView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using CkeckIn.Models.Questions.Thread;

namespace CkeckIn.Models.Questions.Discipline
{
    public class DisciplineView
    {
        [Display(Name = "Ид дисциплины")]
        public Guid DisciplineId { get; set; }

        [Display(Name ="Название дисциплины")]
        public string DisciplineName { get; set; }

        [Display(Name = "Темы")]
        public List<ThreadView> ThreadViews { get; set; }
    }
}

src/CkeckIn/Models/Questions/Question/QuestionCreateView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using CkeckIn.Models.Questions.Thread;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CkeckIn.Models.Questions.Question
{
    public class QuestionCreateView
    {
        public List<SelectListItem> ThreadSelectList { get; set; }

        [Display(Name ="Тема")]
        public Guid ThreadId { get; set; }

        [Display(Name ="Текст вопроса")]
        public string QuestionMessage { get; set; }

        [Display(Name ="Сложность вопроса")]
        public short Strong { get; set; }
    }
}

src/CkeckIn/Models/Questions/Question/QuestionDetailView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CkeckIn.Models.Questions.Answer;


namespace CkeckIn.Models.Questions.Question
{
    public class QuestionDetailView : QuestionView
    {
        public List<AnswerView> AnswerViews { get; set; }
    }
}

src/CkeckIn/Models/Questions/Question/QuestionEntity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using CkeckIn.Models.Questions.Answer;
using CkeckIn.Models.Questions.Thread;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace CkeckIn.Models.Questions.Question
{
    public class QuestionEntity
    {
        public Guid QuestionId { get; set; }
        public string QuestionMessage { get; set; }
        public short Strong { get; set; }

        public Guid RepositoryId { get; set; }

        //------------------------------------------------------------------

        public Guid CreatorId { get; set; }
        public virtual ApplicationUser CreatorEntity { get; set; }

        //------------------------------------------------------------------

        #region Discipline
        public Guid ThreadId { get; set; }
        public virtual ThreadEntity ThreadEntity { get; set; }
        #endregion

        //------------------------------------------------------------------

        public virtual List<AnswerEntity> AnswerEntities { get; set; } = new List<AnswerEntity>(4);
        public int NumberOfAnswers => AnswerEntities.Count;
        public QuestionView AsView()
        {
            Mapper.Initialize
            (
                c => c.CreateMap<QuestionEntity, QuestionView>()
                .ForMember(m => m.ThreadName, m => m.MapFrom(r => r.ThreadEntity.ThreadName))
                .ForMember(m => m.DisciplineName, m => m.MapFrom(r => r.ThreadEntity.DisciplineEntity.DisciplineName))

            );
            return Mapper.Map<QuestionView>(this);
        }

        public QuestionDetailView AsDetailView()
        {
            Mapper.Initialize
                (
                    c => c.CreateMap<QuestionEntity, QuestionDetailView>()
                    .ForMember(m => m.ThreadName, m => m.MapFrom(r => r.ThreadEntity.ThreadName))
                    .ForMember(m => m.DisciplineName, m => m.MapFrom(r => r.ThreadEntity.DisciplineEntity.DisciplineName))
                    .ForMember(m => m.AnswerViews, m => m.MapFrom(r => r.AnswerEntities.Select(d => d.AsView()).ToList()))
                );
            return Mapper.Map<QuestionDetailView>(this);
        }

        public static QuestionEntity Factory(QuestionCreateView view, Guid creatorId)
        {
            Mapper.Initialize
            (
                c => c.CreateMap<QuestionCreateView, QuestionEntity>()
                .ForMember(m => m.QuestionId, m => m.MapFrom(r => Guid.NewGuid()))
                .ForMember(m => m.CreatorId, m => m.UseValue(creatorId))
            );
            return Mapper.Map<QuestionEntity>(view);
        }

        public static void Configuration(EntityTypeBuilder<QuestionEntity> b)
        {
            b.HasKey(p => p.QuestionId);
            b.Property(p => p.QuestionMessage).HasMaxLength(1024);

            b.HasMany(p => p.AnswerEntities).WithOne(p => p.QuestionEntity).HasForeignKey(p => p.QuestionId);
            b.HasOne(p => p.ThreadEntity).WithMany(p => p.QuestionEntities).HasForeignKey(p => p.ThreadId);
            b.HasOne(p => p.CreatorEntity).WithMany().HasForeignKey(p => p.CreatorId);

            
            //b.HasOne(p => p.CreatorEntity).WithMany().HasForeignKey(p => p.CreatorId);
        }
    }
}

src/CkeckIn/Models/Questions/Question/QuestionView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using CkeckIn.Data;
using CkeckIn.Models.Questions.Answer;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CkeckIn.Models.Questions.Question
{
    public class QuestionViewModel
    {
        public CrudOperationAction? Action { get; set; }
        public List<QuestionView> QuestionViews { get; set; }
        public List<SelectListItem> ThreadItems { get; set; }
    }

    public class QuestionView
    {
        [Display(Name ="Ид вопроса")]
        public Guid QuestionId { get; set; }

        //===========================================

        [Display(Name ="Ид темы")]
        public Guid ThreadId { get; set; }

        [Display(Name ="Тема")]
        public string ThreadName { get; set; }

        [Display(Name ="Ид дисциплины")]
        public Guid DisciplineId { get; set; }

        [Display(Name ="Дисциплина")]
        public string DisciplineName { get; set; }
        //===========================================

        [Display(Name ="Вопрос")]
        public string QuestionMessage { get; set; }

        [Display(Name ="Создан")]
        public DateTime CreationDate { get; set; }

        [Display(Name ="Ответов")]
        public int NumberOfAnswers { get; set; }

        public string QuestionRowStatus => NumberOfAnswers < 3 ? "danger" : string.Empty;

        [Display(Name ="Сложность")]
        public short Strong { get; set; }
    }
}

src/CkeckIn/Models/Questions/RepositoryView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CkeckIn.Models.Questions.Discipline;
using CkeckIn.Models.Questions.Question;
using CkeckIn.Models.Questions.Test.Abstract;
using CkeckIn.Models.Questions.Thread;

namespace CkeckIn.Models.Questions
{
    public class RepositoryView
    {
        public List<DisciplineView> DisciplineViews { get; set; }
        public List<ThreadView> ThreadViews { get; set; }
        public List<TestView> TestViews { get; set; }
        public List<QuestionView> QuestionViews { get; set; }
    }
}

src/CkeckIn/Models/Questions/Teacher/TeacherAttachedDisciplineEntity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CkeckIn.Models.Questions.Teacher
{
    public class TeacherAttachedDisciplineEntity
    {
    }
}

src/CkeckIn/Controllers/Admin.ThreadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CkeckIn.Data;
using CkeckIn.Models;
using CkeckIn.Models.Questions.Thread;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace CkeckIn.Controllers
{
    public class ThreadController : Controller
    {
        //=======================================================================================
        public IActionResult Index(Guid? id)
        {
            using (var client = new ThreadRepository())
            {
                return View(new ThreadViewModel
                {
                    ThreadViews = client.TakeAllView(),
                    DisciplineItems = new SelectList(client.Client.DisciplineEntities.ToList(), "DisciplineId", "DisciplineName", id)
                });
            }
        }

        public IActionResult Detail(Guid? id)
        {
            using (var client = new ThreadRepository())
            {
                ThreadEntity entity = client.FindById(id);

                if (entity == null)
                {
                    return View("NotFoundPageView", new NotFoundPageView
                    {
                        Action = "ViewThread",
                        Controller = "Question",
                        Title = "Выберите одну из тем",
                        Message = "Не удалось найти выбранную тему",
                        EntitySelectList = new SelectList(client.TakeAll(), "ThreadId", "ThreadName"),
                        ReturnUrl = "Question/Index"
                    });
                }

                return View(entity.AsDetailView());
            }
        }

        /// <summary>
        /// Добавить вопрос
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Create(Guid id)
        {
            using (var client = new ApplicationDbContext())
            {
                return View(new ThreadCreateView
                {
                    DisciplineId = id,
                    DisciplineSelectList = new SelectList(client.DisciplineEntities.ToList(), "DisciplineId", "DisciplineName", id)
                });
            }
        }

        /// <summary>
        /// Добавить вопрос
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ThreadCreateView view)
        {
            using (var client = new ApplicationDbContext())
            {
                if (client.DisciplineEntities.Any(e => e.DisciplineId == view.DisciplineId))
                {
                    client.ThreadEntities.Add(ThreadEntity.Factory(view));
                    client.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    view.DisciplineSelectList = new SelectList(client.DisciplineEntities.ToList(), "DisciplineId", "DisciplineName");
                    ModelState.AddModelError(nameof(view.DisciplineId), "Discipline not found");
                }
                return View(view);
            }
        }
    }
}

src/CkeckIn/Views/Question/AddAnswer.cshtml
@model CkeckIn.Models.Questions.Answer.AnswerCreateView

@{
    ViewData["Title"] = "Добавление нового ответа";
}

<div class="row">
    <div class="col-md-8 col-xs-8">
        <div class="x_panel">
            <div class="x_title">
                <h2>
                    <i class="fa fa-align-left"></i>
                    @Html.ActionLink("Репозиторий", "Index", "Repository") >
                    @Html.ActionLink("Дисцилплины", "Index", "Discipline") >
                    @Html.ActionLink("Темы", "Index", "Thread") >
                    @Html.ActionLink("Список вопросов", "Index", "Question") >
                    <b>
                        @Html.ActionLink("Добавление нового ответа", "AddAnswer", "Question")
                    </b>
                </h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <form asp-action="AddAnswer">
                    <div class="form-horizontal">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="form-group">
                            <label asp-for="QuestionId" class="col-md-2 control-label"></label>
                            <div class="col-md-10">
                                <select asp-for="QuestionId" class="select2_single form-control" asp-items="@Model.QuestionSelectList"></select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label asp-for="AnswerMessage" class="col-md-2 control-label"></label>
                            <div class="col-md-10">
                                <input asp-for="AnswerMessage" class="form-control" />
                                <span asp-validation-for="AnswerMessage" class="text-danger" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="Mark" class="col-md-2 control-label"></label>
                            <div class="col-md-10">
                                <input asp-for="Mark" class="form-control" />
                                <span asp-validation-for="Mark" class="text-danger" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Добавить новый ответ" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    

    @Html.Partial("PageDescriptionView", new PageDescriptionView
    {
        Title = "Подсказка",
        Messsage = "На этой странице вы можете добавить ответ на вопрос, выбрав его; укажите текст ответа и оценку за сам ответ. Оценка может быть 0 - если ответ не верный и 1, если верный. Так же вы можете использовать свою систему баллов, указав в самом тесте данную опцию."
    })

</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/CkeckIn/Views/Question/Create.cshtml
@model CkeckIn.Models.Questions.Question.QuestionCreateView

@{
    ViewData["Title"] = "Добавление нового вопроса";
}


<div class="row">
    <div class="col-md-8 col-xs-8">
        <div class="x_panel">
            <div class="x_title">
                <h2>
                    <i class="fa fa-align-left"></i>
                    @Html.ActionLink("Репозиторий", "Index", "Repository") >
                    @Html.ActionLink("Дисцилплины", "Index", "Discipline") >
                    @Html.ActionLink("Темы", "Index", "Thread") >
                    @Html.ActionLink("Список вопросов", "Index", "Question") >
                    <b>
                        @Html.ActionLink("Добавление нового вопроса", "Create", "Question")
                    </b>

                </h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <form asp-action="Create">
                    <div class="form-horizontal">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="ThreadId" class="col-md-2 control-label"></label>
                            <div class="col-md-10">
                                <select asp-for="ThreadId" class="select2_single form-control" asp-items="@Model.ThreadSelectList"></select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="QuestionMessage" class="col-md-2 control-label"></label>
                            <div class="col-md-10">
                                <input asp-for="QuestionMessage" class="form-control" />
                                <span asp-validation-for="QuestionMessage" class="text-danger" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="Strong" class="col-md-2 control-label"></label>
                            <div class="col-md-10">
                                <input asp-for="Strong" class="form-control" />
                                <span asp-validation-for="Strong" class="text-danger" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    @Html.Partial("PageDescriptionView", new PageDescriptionView
    {
        Title = "Подсказка",
        Messsage = "На этой странице вы можете добавить новый вопрос, укажите его текст, установить сложность и выбирите тему вопроса. Сложность вопроса нужна, если тест будет формироваться по сложности вопроса."
    })
</div>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/CkeckIn/Views/Question/Detail.cshtml
@model CkeckIn.Models.Questions.Question.QuestionDetailView

@{
    ViewData["Title"] = "ViewQuestion";
    ViewData["Index"] = Model.QuestionId;
}

<div class="row">

    <div class="col-md-6 col-sm-6 col-xs-6">
        <div class="x_panel" style="min-height: 400px;">
            <div class="x_title">
                <h2>
                    <b>Вопрос:</b>
                    @Model.QuestionMessage
                </h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.QuestionId)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.QuestionId)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.ThreadId)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.ThreadId)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.ThreadName)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.ThreadName)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.DisciplineId)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.DisciplineId)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.DisciplineName)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.DisciplineName)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.QuestionMessage)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.QuestionMessage)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.CreationDate)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.CreationDate)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.NumberOfAnswers)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.NumberOfAnswers)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Strong)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Strong)
                    </dd>
                </dl>

            </div>
        </div>
    </div>

    @Html.Partial("ViewAnswers", Model.AnswerViews)
</div>

src/CkeckIn/Views/Question/Index.cshtml
@using CkeckIn.Data
@model CkeckIn.Models.Questions.Question.QuestionViewModel

@{
    ViewData["Title"] = "Index";
}

<div class="row">
    @Html.Partial("Index/ThreadSelector", Model.ThreadItems)

    <div class="col-md-12 col-sm-12 col-xs-12">
        @Html.Partial("Index/QuestionsTable", Model.QuestionViews)
    </div>
</div>

  <!-- PNotify -->
<script type="text/javascript" src="~/lib/gentelella/production/js/notify/pnotify.core.js"></script>
<script type="text/javascript" src="~/lib/gentelella/production/js/notify/pnotify.buttons.js"></script>
<script type="text/javascript" src="~/lib/gentelella/production/js/notify/pnotify.nonblock.js"></script>

@if (Model.Action == CrudOperationAction.Created)
{
    <script type="text/javascript">
        $(function () {
            new PNotify({
                title: 'Новый вопрос',
                text: 'Вы успешно добавили новый вопрос!',
                type: 'success'
            });
        });
    
    </script>
}

src/CkeckIn/Views/Question/ViewAnswer.cshtml
@model CkeckIn.Models.Questions.Answer.AnswerDetailView

@{
    ViewData["Title"] = "ViewAnswer";
}

<h2>ViewAnswer</h2>

<div>
    <h4>AnswerDetailView</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.QuestionId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.QuestionId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AnswerId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AnswerId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AnswerMessage)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AnswerMessage)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Mark)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Mark)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

src/CkeckIn/Views/Question/ViewAnswers.cshtml
@model IEnumerable<CkeckIn.Models.Questions.Answer.AnswerView>

@{
    ViewData["Title"] = "ViewAnswers";
}

<div class="col-md-6 col-sm-6 col-xs-6">
    <div class="x_panel" style="min-height: 400px;">
        <div class="x_title">
            <h2>
                @Html.ActionLink("Добавить ответ", "AddAnswer", new {id = ViewData["Index"] })
            </h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.AnswerMessage)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Mark)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.ActionLink(item.AnswerMessage, "ViewAnswer", new {id = item.AnswerId})
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Mark)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>